In [1]:
from utils.deadlock import *

E58) a)

In [2]:
process_names = ['A', 'B', 'C', 'D']

avail = np.array([1, 2, 7])

alloc = np.array([[5, 1, 1],
                  [0, 2, 0],
                  [4, 2, 0],
                  [2, 2, 0]])
print("Alloc:\n", alloc)

maximum = np.array([[6, 1, 2],
                    [2, 7, 2],
                    [7, 6, 3],
                    [6, 5, 1]])
print("Max:\n", maximum)

need = np.subtract(maximum, alloc)
print("Subtracting Alloc from Max:\n", need)

isStateSafe = calc_safe_sequence(avail, alloc, need, process_names)

Alloc:
 [[5 1 1]
 [0 2 0]
 [4 2 0]
 [2 2 0]]
Max:
 [[6 1 2]
 [2 7 2]
 [7 6 3]
 [6 5 1]]
Subtracting Alloc from Max:
 [[1 0 1]
 [2 5 2]
 [3 4 3]
 [4 3 1]]

Process A comparing need with work: [1 0 1] <= [1 2 7]
Process A completed
work = work + alloc[A]: [1 2 7] + [5 1 1] = [6 3 8]

Process A already finished
Process B comparing need with work: [2 5 2] <= [6 3 8]
Process B has not enough resources
Process C comparing need with work: [3 4 3] <= [6 3 8]
Process C has not enough resources
Process D comparing need with work: [4 3 1] <= [6 3 8]
Process D completed
work = work + alloc[D]: [6 3 8] + [2 2 0] = [8 5 8]

Process A already finished
Process B comparing need with work: [2 5 2] <= [8 5 8]
Process B completed
work = work + alloc[B]: [8 5 8] + [0 2 0] = [8 7 8]

Process A already finished
Process B already finished
Process C comparing need with work: [3 4 3] <= [8 7 8]
Process C completed
work = work + alloc[C]: [8 7 8] + [4 2 0] = [12  9  8]

All processes are finished
Safe sequence: 

E58) b) D asks (0, 2, 1) more resources

In [3]:
request = np.array([0, 2, 1])
process = 3
new_alloc, new_need = try_grant_request(avail, alloc, need, process, request, process_names)

request <= need[D] ([0 2 1] <= [4 3 1]) OK
request <= avail ([0 2 1] <= [1 2 7]) OK
avail = avail - request: [1 2 7] - [0 2 1] = [1 0 6]
need = need - request: [4 3 1] - [0 2 1] = [4 1 0]
alloc[process] = alloc[process] + request: [2 2 0] + [0 2 1] = [2 4 1]

Process A comparing need with work: [1 0 1] <= [1 0 6]
Process A completed
work = work + alloc[A]: [1 0 6] + [5 1 1] = [6 1 7]

Process A already finished
Process B comparing need with work: [2 5 2] <= [6 1 7]
Process B has not enough resources
Process C comparing need with work: [3 4 3] <= [6 1 7]
Process C has not enough resources
Process D comparing need with work: [4 1 0] <= [6 1 7]
Process D completed
work = work + alloc[D]: [6 1 7] + [2 4 1] = [8 5 8]

Process A already finished
Process B comparing need with work: [2 5 2] <= [8 5 8]
Process B completed
work = work + alloc[B]: [8 5 8] + [0 2 0] = [8 7 8]

Process A already finished
Process B already finished
Process C comparing need with work: [3 4 3] <= [8 7 8]
Process C com

E58) c) B asks (1, 2, 1) more resources

In [4]:
request = np.array([1, 2, 1])
process = 1
new_alloc, new_need = try_grant_request(avail, alloc, need, process, request, process_names)

request <= need[B] ([1 2 1] <= [2 5 2]) OK
request <= avail ([1 2 1] <= [1 2 7]) OK
avail = avail - request: [1 2 7] - [1 2 1] = [0 0 6]
need = need - request: [2 5 2] - [1 2 1] = [1 3 1]
alloc[process] = alloc[process] + request: [0 2 0] + [1 2 1] = [1 4 1]

Process A comparing need with work: [1 0 1] <= [0 0 6]
Process A has not enough resources
Process B comparing need with work: [1 3 1] <= [0 0 6]
Process B has not enough resources
Process C comparing need with work: [3 4 3] <= [0 0 6]
Process C has not enough resources
Process D comparing need with work: [4 3 1] <= [0 0 6]
Process D has not enough resources

There is no safe sequence
Request [1 2 1] for process B is not granted because the state would be unsafe


E71)

In [5]:
process_names = ['P1', 'P2', 'P3']
resource_names = ['R1', 'R2']

alloc = np.array([[3, 1],
                  [2, 3],
                  [3, 0]])
print("Alloc:\n", alloc)

maximum = np.array([[7, 3],
                    [3, 3],
                    [5, 4]])
print("Max:\n", maximum)

R1 = 10
R2 = 12

avail = np.array([R1-np.sum(alloc[:,0]), R2-np.sum(alloc[:,1])])
print("Avail:\n", avail)

need = np.subtract(maximum, alloc)
print("Subtracting Alloc from Max:\n", need)

calc_safe_sequence(avail, alloc, need, process_names)

Alloc:
 [[3 1]
 [2 3]
 [3 0]]
Max:
 [[7 3]
 [3 3]
 [5 4]]
Avail:
 [2 8]
Subtracting Alloc from Max:
 [[4 2]
 [1 0]
 [2 4]]

Process P1 comparing need with work: [4 2] <= [2 8]
Process P1 has not enough resources
Process P2 comparing need with work: [1 0] <= [2 8]
Process P2 completed
work = work + alloc[P2]: [2 8] + [2 3] = [ 4 11]

Process P1 comparing need with work: [4 2] <= [ 4 11]
Process P1 completed
work = work + alloc[P1]: [ 4 11] + [3 1] = [ 7 12]

Process P1 already finished
Process P2 already finished
Process P3 comparing need with work: [2 4] <= [ 7 12]
Process P3 completed
work = work + alloc[P3]: [ 7 12] + [3 0] = [10 12]

All processes are finished
Safe sequence: ['P2', 'P1', 'P3']


True

In [6]:
request = np.array([3, 1])
process = 0
alloc, need = try_grant_request(avail, alloc, need, process, request, process_names)

request <= need[P1] ([3 1] <= [4 2]) OK
Request [3 1] for process P1 is not granted because it exceeds the available resources request > avail ([3 1] > [2 8])


E72)

In [7]:
process_names = ['P1', 'P2', 'P3', 'P4']

avail = np.array([1, 5, 2, 0])

alloc = np.array([[1, 0, 0, 0],
                  [1, 2, 3, 4],
                  [0, 2, 2, 2],
                  [0, 0, 1, 3]])
print("Alloc:\n", alloc)

need = np.array([[0, 7, 5, 0],
                 [1, 0, 0, 2],
                 [0, 0, 2, 0],
                 [0, 6, 4, 2]])
print("Need:\n", need)

isStateSafe = calc_safe_sequence(avail, alloc, need, process_names)

Alloc:
 [[1 0 0 0]
 [1 2 3 4]
 [0 2 2 2]
 [0 0 1 3]]
Need:
 [[0 7 5 0]
 [1 0 0 2]
 [0 0 2 0]
 [0 6 4 2]]

Process P1 comparing need with work: [0 7 5 0] <= [1 5 2 0]
Process P1 has not enough resources
Process P2 comparing need with work: [1 0 0 2] <= [1 5 2 0]
Process P2 has not enough resources
Process P3 comparing need with work: [0 0 2 0] <= [1 5 2 0]
Process P3 completed
work = work + alloc[P3]: [1 5 2 0] + [0 2 2 2] = [1 7 4 2]

Process P1 comparing need with work: [0 7 5 0] <= [1 7 4 2]
Process P1 has not enough resources
Process P2 comparing need with work: [1 0 0 2] <= [1 7 4 2]
Process P2 completed
work = work + alloc[P2]: [1 7 4 2] + [1 2 3 4] = [2 9 7 6]

Process P1 comparing need with work: [0 7 5 0] <= [2 9 7 6]
Process P1 completed
work = work + alloc[P1]: [2 9 7 6] + [1 0 0 0] = [3 9 7 6]

Process P1 already finished
Process P2 already finished
Process P3 already finished
Process P4 comparing need with work: [0 6 4 2] <= [3 9 7 6]
Process P4 completed
work = work + allo

E72) P4 asks (0, 5, 2, 0) more resources

In [8]:
request = np.array([0, 5, 2, 0])
process = 3
new_alloc, new_need = try_grant_request(avail, alloc, need, process, request, process_names)

request <= need[P4] ([0 5 2 0] <= [0 6 4 2]) OK
request <= avail ([0 5 2 0] <= [1 5 2 0]) OK
avail = avail - request: [1 5 2 0] - [0 5 2 0] = [1 0 0 0]
need = need - request: [0 6 4 2] - [0 5 2 0] = [0 1 2 2]
alloc[process] = alloc[process] + request: [0 0 1 3] + [0 5 2 0] = [0 5 3 3]

Process P1 comparing need with work: [0 7 5 0] <= [1 0 0 0]
Process P1 has not enough resources
Process P2 comparing need with work: [1 0 0 2] <= [1 0 0 0]
Process P2 has not enough resources
Process P3 comparing need with work: [0 0 2 0] <= [1 0 0 0]
Process P3 has not enough resources
Process P4 comparing need with work: [0 1 2 2] <= [1 0 0 0]
Process P4 has not enough resources

There is no safe sequence
Request [0 5 2 0] for process P4 is not granted because the state would be unsafe


E72) P1 asks (0, 3, 2, 0) more resources

In [9]:
request = np.array([0, 3, 2, 0])
process = 0
new_alloc, new_need = try_grant_request(avail, new_alloc, new_need, process, request, process_names)

request <= need[P1] ([0 3 2 0] <= [0 7 5 0]) OK
request <= avail ([0 3 2 0] <= [1 5 2 0]) OK
avail = avail - request: [1 5 2 0] - [0 3 2 0] = [1 2 0 0]
need = need - request: [0 7 5 0] - [0 3 2 0] = [0 4 3 0]
alloc[process] = alloc[process] + request: [1 0 0 0] + [0 3 2 0] = [1 3 2 0]

Process P1 comparing need with work: [0 4 3 0] <= [1 2 0 0]
Process P1 has not enough resources
Process P2 comparing need with work: [1 0 0 2] <= [1 2 0 0]
Process P2 has not enough resources
Process P3 comparing need with work: [0 0 2 0] <= [1 2 0 0]
Process P3 has not enough resources
Process P4 comparing need with work: [0 1 2 2] <= [1 2 0 0]
Process P4 has not enough resources

There is no safe sequence
Request [0 3 2 0] for process P1 is not granted because the state would be unsafe
