In [52]:
import numpy as np


def calc_safe_sequence(avail, alloc, need, process_names):
    n = len(alloc)     # number of processes
    m = len(alloc[0])  # number of resources
    safe_sequence = []
    work = avail
    finish = [False] * n

    while True:
        print()
        for i in range(n):
            print(f'Process {process_names[i]}', end=' ')
            if not finish[i]:
                print('comparing need with work:', need[i], '<=', work)
                if all(need[i][j] > work[j] for j in range(m)):
                    print(f'Process {process_names[i]} has not enough resources')
                    break
                else:
                    print(f'Process {process_names[i]} completed')
                    print('work = work + alloc:', work, '+', alloc[i], '=', np.add(work, alloc[i]))
                    work = np.add(work, alloc[i])
                    finish[i] = True
                    safe_sequence.append(process_names[i])
                continue
            print('already finished')

        if all(finish):
            print()
            print('All processes are finished')
            print('Safe sequence:', safe_sequence)
            break

E58) a)

In [56]:
process_names = ['A', 'B', 'C', 'D']

avail = np.array([1, 2, 7])

alloc = np.array([[5, 1, 1],
                  [0, 2, 0],
                  [4, 2, 0],
                  [2, 2, 0]])
print("Alloc:\n", alloc)

maximum = np.array([[6, 1, 2],
                    [2, 7, 2],
                    [7, 6, 3],
                    [6, 5, 1]])
print("Max:\n", maximum)

need = np.subtract(maximum, alloc)
print("Subtracting Alloc from Max:\n", need)

calc_safe_sequence(avail, alloc, need, process_names)

Alloc:
 [[5 1 1]
 [0 2 0]
 [4 2 0]
 [2 2 0]]
Max:
 [[6 1 2]
 [2 7 2]
 [7 6 3]
 [6 5 1]]
Subtracting Alloc from Max:
 [[1 0 1]
 [2 5 2]
 [3 4 3]
 [4 3 1]]

Process A comparing need with work: [1 0 1] <= [1 2 7]
Process A completed
work = work + alloc: [1 2 7] + [5 1 1] = [6 3 8]
Process B comparing need with work: [2 5 2] <= [6 3 8]
Process B completed
work = work + alloc: [6 3 8] + [0 2 0] = [6 5 8]
Process C comparing need with work: [3 4 3] <= [6 5 8]
Process C completed
work = work + alloc: [6 5 8] + [4 2 0] = [10  7  8]
Process D comparing need with work: [4 3 1] <= [10  7  8]
Process D completed
work = work + alloc: [10  7  8] + [2 2 0] = [12  9  8]

All processes are finished
Safe sequence: ['A', 'B', 'C', 'D']


E58) b) D asks (0, 2, 1) more resources

In [58]:
request = np.array([0, 2, 1])
process = 3
if all(request[i] <= need[process][i] for i in range(len(request))):
    if all(request[i] <= avail[i] for i in range(len(request))):
        print(f'Request {request} for process {process_names[process]} is granted')
        print('avail = avail - request:', avail, '-', request, '=', np.subtract(avail, request))
        avail = np.subtract(avail, request)
        print('alloc[process] = alloc[process] + request:',
              alloc[process], '+', request, '=', np.add(alloc[process], request))
        alloc[process] = np.add(alloc[process], request)
        print('need = need - request:', need[process], '-', request, '=', np.subtract(need[process], request))
        need[process] = np.subtract(need[process], request)
    else:
        print(f'Request {request} for process {process_names[process]} '
              f'is not granted because it exceeds the available resources '
              f'(request > avail)'
else:
    print(f'Request {request} for process {process_names[process]} '
          f'is not granted because it exceeds the maximum resources')

calc_safe_sequence(avail, alloc, need, process_names)

Request [0 2 1] for process D is not granted because it exceeds the maximum resources

Process A comparing need with work: [1 0 1] <= [1 0 6]
Process A completed
work = work + alloc: [1 0 6] + [5 1 1] = [6 1 7]
Process B comparing need with work: [2 5 2] <= [6 1 7]
Process B completed
work = work + alloc: [6 1 7] + [0 2 0] = [6 3 7]
Process C comparing need with work: [3 4 3] <= [6 3 7]
Process C completed
work = work + alloc: [6 3 7] + [4 2 0] = [10  5  7]
Process D comparing need with work: [4 1 0] <= [10  5  7]
Process D completed
work = work + alloc: [10  5  7] + [2 4 1] = [12  9  8]

All processes are finished
Safe sequence: ['A', 'B', 'C', 'D']


In [ ]:
process_names = ['A', 'B', 'C', 'D']

avail = np.array([0, 0, 6]) # B asks (1, 2, 1) more resources

alloc = np.array([[5, 1, 1],
                  [1, 4, 1],   # B asks (1, 2, 1) more resources
                  [4, 2, 0],
                  [2, 4, 1]])
print("Alloc:\n", alloc)

maximum = np.array([[6, 1, 2],
                    [2, 7, 2],
                    [7, 6, 3],
                    [6, 5, 1]])
print("Max:\n", maximum)

need = calc_need_matrix(alloc, maximum)
print("Subtracting Alloc from Max:\n", need)

calc_safe_sequence(avail, alloc, need, process_names)