In [1]:
import numpy as np


def calc_safe_sequence(avail, alloc, need, process_names):
    n = len(alloc)     # number of processes
    m = len(alloc[0])  # number of resources
    safe_sequence = []
    work = avail
    finish = [False] * n

    while True:
        print()
        for i in range(n):
            print(f'Process {process_names[i]}', end=' ')
            if finish[i]:
                print('already finished')
                continue

            print('comparing need with work:', need[i], '<=', work)
            if (need[i] > work).any():
                print(f'Process {process_names[i]} has not enough resources')
                continue

            print(f'Process {process_names[i]} completed')
            print('work = work + alloc:', work, '+', alloc[i], '=', np.add(work, alloc[i]))
            work = np.add(work, alloc[i])
            finish[i] = True
            safe_sequence.append(process_names[i])
            continue

        if all(finish):
            print()
            print('All processes are finished')
            print('Safe sequence:', safe_sequence)
            break

        if not any(finish):
            print()
            print('There is no safe sequence')
            break

def try_grant_request(avail, alloc, need, process, request):
    if (request <= need[process]).all():
        if (request <= avail).all():
            print(f'Request {request} for process {process_names[process]} is granted')
            print('avail = avail - request:', avail, '-', request, '=', np.subtract(avail, request))
            avail = np.subtract(avail, request)
            print('alloc[process] = alloc[process] + request:',
                  alloc[process], '+', request, '=', np.add(alloc[process], request))
            alloc[process] = np.add(alloc[process], request)
            print('need = need - request:', need[process], '-', request, '=', np.subtract(need[process], request))
            need[process] = np.subtract(need[process], request)
            calc_safe_sequence(avail, alloc, need, process_names)
        else:
            print(f'Request {request} for process {process_names[process]} '
                  f'is not granted because it exceeds the available resources '
                  f'request > avail ({request} > {avail})')
    else:
        print(f'Request {request} for process {process_names[process]} '
              f'is not granted because it exceeds the maximum resources')

E58) a)

In [2]:
process_names = ['A', 'B', 'C', 'D']

avail = np.array([1, 2, 7])

alloc = np.array([[5, 1, 1],
                  [0, 2, 0],
                  [4, 2, 0],
                  [2, 2, 0]])
print("Alloc:\n", alloc)

maximum = np.array([[6, 1, 2],
                    [2, 7, 2],
                    [7, 6, 3],
                    [6, 5, 1]])
print("Max:\n", maximum)

need = np.subtract(maximum, alloc)
print("Subtracting Alloc from Max:\n", need)

calc_safe_sequence(avail, alloc, need, process_names)

Alloc:
 [[5 1 1]
 [0 2 0]
 [4 2 0]
 [2 2 0]]
Max:
 [[6 1 2]
 [2 7 2]
 [7 6 3]
 [6 5 1]]
Subtracting Alloc from Max:
 [[1 0 1]
 [2 5 2]
 [3 4 3]
 [4 3 1]]

Process A comparing need with work: [1 0 1] <= [1 2 7]
Process A completed
work = work + alloc: [1 2 7] + [5 1 1] = [6 3 8]
Process B comparing need with work: [2 5 2] <= [6 3 8]
Process B has not enough resources
Process C comparing need with work: [3 4 3] <= [6 3 8]
Process C has not enough resources
Process D comparing need with work: [4 3 1] <= [6 3 8]
Process D completed
work = work + alloc: [6 3 8] + [2 2 0] = [8 5 8]

Process A already finished
Process B comparing need with work: [2 5 2] <= [8 5 8]
Process B completed
work = work + alloc: [8 5 8] + [0 2 0] = [8 7 8]
Process C comparing need with work: [3 4 3] <= [8 7 8]
Process C completed
work = work + alloc: [8 7 8] + [4 2 0] = [12  9  8]
Process D already finished

All processes are finished
Safe sequence: ['A', 'D', 'B', 'C']


E58) b) D asks (0, 2, 1) more resources

In [3]:
request = np.array([0, 2, 1])
process = 3
try_grant_request(avail, alloc, need, process, request)

Request [0 2 1] for process D is granted
avail = avail - request: [1 2 7] - [0 2 1] = [1 0 6]
alloc[process] = alloc[process] + request: [2 2 0] + [0 2 1] = [2 4 1]
need = need - request: [4 3 1] - [0 2 1] = [4 1 0]

Process A comparing need with work: [1 0 1] <= [1 0 6]
Process A completed
work = work + alloc: [1 0 6] + [5 1 1] = [6 1 7]
Process B comparing need with work: [2 5 2] <= [6 1 7]
Process B has not enough resources
Process C comparing need with work: [3 4 3] <= [6 1 7]
Process C has not enough resources
Process D comparing need with work: [4 1 0] <= [6 1 7]
Process D completed
work = work + alloc: [6 1 7] + [2 4 1] = [8 5 8]

Process A already finished
Process B comparing need with work: [2 5 2] <= [8 5 8]
Process B completed
work = work + alloc: [8 5 8] + [0 2 0] = [8 7 8]
Process C comparing need with work: [3 4 3] <= [8 7 8]
Process C completed
work = work + alloc: [8 7 8] + [4 2 0] = [12  9  8]
Process D already finished

All processes are finished
Safe sequence: ['A', 

E58) c) B asks (1, 2, 1) more resources

In [4]:
request = np.array([1, 2, 1])
process = 1
try_grant_request(avail, alloc, need, process, request)

Request [1 2 1] for process B is granted
avail = avail - request: [1 2 7] - [1 2 1] = [0 0 6]
alloc[process] = alloc[process] + request: [0 2 0] + [1 2 1] = [1 4 1]
need = need - request: [2 5 2] - [1 2 1] = [1 3 1]

Process A comparing need with work: [1 0 1] <= [0 0 6]
Process A has not enough resources
Process B comparing need with work: [1 3 1] <= [0 0 6]
Process B has not enough resources
Process C comparing need with work: [3 4 3] <= [0 0 6]
Process C has not enough resources
Process D comparing need with work: [4 1 0] <= [0 0 6]
Process D has not enough resources

There is no safe sequence


E71)

In [5]:
process_names = ['P1', 'P2', 'P3']
resource_names = ['R1', 'R2']

alloc = np.array([[3, 1],
                  [2, 3],
                  [3, 0]])
print("Alloc:\n", alloc)

maximum = np.array([[7, 3],
                    [3, 3],
                    [5, 4]])
print("Max:\n", maximum)

R1 = 10
R2 = 12

avail = np.array([R1-np.sum(alloc[:,0]), R2-np.sum(alloc[:,1])])
print("Avail:\n", avail)

need = np.subtract(maximum, alloc)
print("Subtracting Alloc from Max:\n", need)

calc_safe_sequence(avail, alloc, need, process_names)

Alloc:
 [[3 1]
 [2 3]
 [3 0]]
Max:
 [[7 3]
 [3 3]
 [5 4]]
Avail:
 [2 8]
Subtracting Alloc from Max:
 [[4 2]
 [1 0]
 [2 4]]

Process P1 comparing need with work: [4 2] <= [2 8]
Process P1 has not enough resources
Process P2 comparing need with work: [1 0] <= [2 8]
Process P2 completed
work = work + alloc: [2 8] + [2 3] = [ 4 11]
Process P3 comparing need with work: [2 4] <= [ 4 11]
Process P3 completed
work = work + alloc: [ 4 11] + [3 0] = [ 7 11]

Process P1 comparing need with work: [4 2] <= [ 7 11]
Process P1 completed
work = work + alloc: [ 7 11] + [3 1] = [10 12]
Process P2 already finished
Process P3 already finished

All processes are finished
Safe sequence: ['P2', 'P3', 'P1']


In [6]:
request = np.array([3, 1])
process = 0
try_grant_request(avail, alloc, need, process, request)

Request [3 1] for process P1 is not granted because it exceeds the available resources request > avail ([3 1] > [2 8])
